/**
 * @file feature_scaler.h
 * @brief Numerical Normalizer for AI Inputs.
 * 
 * Replicates the logic of sklearn.preprocessing.MinMaxScaler
 * to ensure C++ inference matches Python training.
 */

#ifndef BLACKBOX_PARSER_FEATURE_SCALER_H
#define BLACKBOX_PARSER_FEATURE_SCALER_H

#include <vector>
#include <string>
#include <array>

namespace blackbox::parser {

    class FeatureScaler {
    public:
        FeatureScaler();
        ~FeatureScaler() = default;

        /**
         * @brief Load scaling parameters from disk.
         * 
         * File Format (generated by blackbox-sim):
         * Line N: "min_value,max_value" for feature N.
         * 
         * @param path Path to scaler_params.txt
         * @return true if loaded successfully
         */
        bool load_parameters(const std::string& path);

        /**
         * @brief Apply normalization to a feature vector in-place.
         * 
         * Formula: x' = (x - min) * scale_factor
         * Where scale_factor = 1 / (max - min)
         * 
         * @param vector The 128-float vector from the Tokenizer
         */
        void transform(std::array<float, 128>& vector) const;

    private:
        // Parallel vectors for SIMD-friendly access
        std::vector<float> min_vals_;
        std::vector<float> scale_factors_; // 1.0 / (max - min)
        
        bool ready_ = false;
    };

} // namespace blackbox::parser

#endif // BLACKBOX_PARSER_FEATURE_SCALER_H